### ISSUE TITLE
[Data conversion] EK80 with simrad-es120-7c import error. 

### ISSUE THREAD

**Issue by m4rkus84** [OSOceanAcoustics/echopype#1391]
### General description of problem

Hi, I'm trying to import a raw file into Echopype but I get an error. It seems related to time...

### Echopype version

echopype 0.6.1

### How did you install Echopype (e.g., conda or pip)

I installed echopype by pip install echopype

### What is your operating system

Windows 11

### Minimal code example

ed = open_raw('C:/Users/Public/Documents/Simrad/EK80/Data/D20240904-T093358.raw', sonar_model='EK80')  # for EK80 file
ed.to_netcdf(save_path='./unpacked_files')

### Error message printouts

```shell
11:30:21  parsing file D20240904-T093358.raw, time of first ping: 2024-Sep-04 09:33:58
C:\anaconda3\envs\my_env_01082024\Lib\site-packages\echopype\convert\set_groups_ek80.py:112: UserWarning: Converting non-nanosecond precision datetime values to nanosecond precision. This behavior can eventually be relaxed in xarray, as it is an artifact from pandas which is now beginning to support non-nanosecond precision values. This warning is caused by passing non-nanosecond np.datetime64 or np.timedelta64 values to the DataArray or Variable constructor; it can be silenced by converting the values to nanosecond precision ahead of time.
  ds = xr.Dataset(
C:\anaconda3\envs\my_env_01082024\Lib\site-packages\echopype\convert\set_groups_ek80.py:236: UserWarning: Converting non-nanosecond precision datetime values to nanosecond precision. This behavior can eventually be relaxed in xarray, as it is an artifact from pandas which is now beginning to support non-nanosecond precision values. This warning is caused by passing non-nanosecond np.datetime64 or np.timedelta64 values to the DataArray or Variable constructor; it can be silenced by converting the values to nanosecond precision ahead of time.
  ds = xr.Dataset(
C:\anaconda3\envs\my_env_01082024\Lib\site-packages\echopype\convert\set_groups_ek80.py:236: UserWarning: Converting non-nanosecond precision datetime values to nanosecond precision. This behavior can eventually be relaxed in xarray, as it is an artifact from pandas which is now beginning to support non-nanosecond precision values. This warning is caused by passing non-nanosecond np.datetime64 or np.timedelta64 values to the DataArray or Variable constructor; it can be silenced by converting the values to nanosecond precision ahead of time.
  ds = xr.Dataset(
C:\anaconda3\envs\my_env_01082024\Lib\site-packages\xarray\coding\times.py:254: RuntimeWarning: invalid value encountered in cast
  flat_num_dates_ns_int = (flat_num_dates * _NS_PER_TIME_DELTA[delta]).astype(
C:\anaconda3\envs\my_env_01082024\Lib\site-packages\echopype\convert\set_groups_ek80.py:563: UserWarning: Converting non-nanosecond precision datetime values to nanosecond precision. This behavior can eventually be relaxed in xarray, as it is an artifact from pandas which is now beginning to support non-nanosecond precision values. This warning is caused by passing non-nanosecond np.datetime64 or np.timedelta64 values to the DataArray or Variable constructor; it can be silenced by converting the values to nanosecond precision ahead of time.
  ds_tmp = xr.Dataset(
C:\anaconda3\envs\my_env_01082024\Lib\site-packages\echopype\convert\set_groups_ek80.py:602: UserWarning: Converting non-nanosecond precision datetime values to nanosecond precision. This behavior can eventually be relaxed in xarray, as it is an artifact from pandas which is now beginning to support non-nanosecond precision values. This warning is caused by passing non-nanosecond np.datetime64 or np.timedelta64 values to the DataArray or Variable constructor; it can be silenced by converting the values to nanosecond precision ahead of time.
  ds_f_start_end = xr.Dataset(
C:\anaconda3\envs\my_env_01082024\Lib\site-packages\echopype\convert\set_groups_ek80.py:750: UserWarning: Converting non-nanosecond precision datetime values to nanosecond precision. This behavior can eventually be relaxed in xarray, as it is an artifact from pandas which is now beginning to support non-nanosecond precision values. This warning is caused by passing non-nanosecond np.datetime64 or np.timedelta64 values to the DataArray or Variable constructor; it can be silenced by converting the values to nanosecond precision ahead of time.
  ds_common = xr.Dataset(
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
File C:\anaconda3\envs\my_env_01082024\Lib\pathlib.py:555, in PurePath.drive(self)
    554 try:
--> 555     return self._drv
    556 except AttributeError:

AttributeError: 'NodePath' object has no attribute '_drv'

During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)
Cell In[14], line 1
----> 1 ed = open_raw('C:/Users/Public/Documents/Simrad/EK80/Data/D20240904-T093358.raw', sonar_model='EK80')  # for EK80 file
      2 ed.to_netcdf(save_path='./unpacked_files')

File C:\anaconda3\envs\my_env_01082024\Lib\site-packages\echopype\convert\api.py:486, in open_raw(raw_file, sonar_model, xml_path, convert_params, storage_options)
    482 tree_dict["Vendor_specific"] = setgrouper.set_vendor()
    484 # Create tree and echodata
    485 # TODO: make the creation of tree dynamically generated from yaml
--> 486 tree = DataTree.from_dict(tree_dict, name="root")
    487 echodata = EchoData(source_file=file_chk, xml_path=xml_chk, sonar_model=sonar_model)
    488 echodata._set_tree(tree)

File C:\anaconda3\envs\my_env_01082024\Lib\site-packages\datatree\datatree.py:360, in DataTree.from_dict(cls, d, name)
    356 if d:
    357     # Populate tree with children determined from data_objects mapping
    358     for path, data in d.items():
    359         # Create and set new node
--> 360         node_name = NodePath(path).name
    361         new_node = cls(name=node_name, data=data)
    362         obj._set_item(
    363             path,
    364             new_node,
    365             allow_overwrite=False,
    366             new_nodes_along_path=True,
    367         )

File C:\anaconda3\envs\my_env_01082024\Lib\site-packages\datatree\treenode.py:34, in NodePath.__new__(cls, *args)
     31 def __new__(cls, *args: str | "NodePath") -> "NodePath":
     32     obj = super().__new__(cls, *args)
---> 34     if obj.drive:
     35         raise ValueError("NodePaths cannot have drives")
     37     if obj.root not in ["/", ""]:

File C:\anaconda3\envs\my_env_01082024\Lib\pathlib.py:557, in PurePath.drive(self)
    555     return self._drv
    556 except AttributeError:
--> 557     self._load_parts()
    558     return self._drv

File C:\anaconda3\envs\my_env_01082024\Lib\pathlib.py:408, in PurePath._load_parts(self)
    407 def _load_parts(self):
--> 408     paths = self._raw_paths
    409     if len(paths) == 0:
    410         path = ''

AttributeError: 'NodePath' object has no attribute '_raw_paths'
Click to add a cell.
```

### Example data

https://drive.google.com/file/d/1ZQ14tQh2UIutJIuEZ5RSAI__MAGr80Wq/view?usp=sharing

### Related existing issues or PRs

I have seen other topic with import errors but I do not see anything related to my issues

**Comment by ctuguinay** [comment]
Could you try converting with the latest Echopype version, 0.9.1?

**Comment by m4rkus84** [comment]
> Could you try converting with the latest Echopype version, 0.9.1?

How can I install version 0.9.1? I installed Echopype just yesterday via conda, but it installed version 0.6.1.

**Comment by ctuguinay** [comment]
@m4rkus84 `conda install echopype=0.9.1` or something like that where you specify the version

**Comment by m4rkus84** [comment]
> @m4rkus84 `conda install echopype=0.9.1` or something like that where you specify the version

I installed version 0.9.0 because 0.9.1 cannot be installed via 'pip install,' as it doesn't seem to be (yet) available. Now the number of errors has decreased, but the import issue still hasn't been resolved, and it returns these errors.

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
File C:\anaconda3\envs\my_env_01082024\Lib\pathlib.py:555, in PurePath.drive(self)
    554 try:
--> 555     return self._drv
    556 except AttributeError:

AttributeError: 'NodePath' object has no attribute '_drv'

During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)
Cell In[9], line 1
----> 1 ed = open_raw('C:/Users/Public/Documents/Simrad/EK80/Data/D20240904-T093358.raw', sonar_model='EK80')  # for EK80 file
      2 ed.to_netcdf(save_path='./unpacked_files')

File C:\anaconda3\envs\my_env_01082024\Lib\site-packages\echopype\utils\prov.py:237, in add_processing_level.<locals>.wrapper.<locals>.inner(*args, **kwargs)
    235 @functools.wraps(func)
    236 def inner(*args, **kwargs):
--> 237     dataobj = func(*args, **kwargs)
    238     if is_echodata:
    239         ed = dataobj

File C:\anaconda3\envs\my_env_01082024\Lib\site-packages\echopype\convert\api.py:540, in open_raw(raw_file, sonar_model, xml_path, include_bot, include_idx, convert_params, storage_options, use_swap, max_chunk_size)
    536 tree_dict["Vendor_specific"] = setgrouper.set_vendor()
    538 # Create tree and echodata
    539 # TODO: make the creation of tree dynamically generated from yaml
--> 540 tree = DataTree.from_dict(tree_dict, name="root")
    541 echodata = EchoData(source_file=file_chk, xml_path=xml_chk, sonar_model=sonar_model)
    542 echodata._set_tree(tree)

File C:\anaconda3\envs\my_env_01082024\Lib\site-packages\datatree\datatree.py:360, in DataTree.from_dict(cls, d, name)
    356 if d:
    357     # Populate tree with children determined from data_objects mapping
    358     for path, data in d.items():
    359         # Create and set new node
--> 360         node_name = NodePath(path).name
    361         new_node = cls(name=node_name, data=data)
    362         obj._set_item(
    363             path,
    364             new_node,
    365             allow_overwrite=False,
    366             new_nodes_along_path=True,
    367         )

File C:\anaconda3\envs\my_env_01082024\Lib\site-packages\datatree\treenode.py:34, in NodePath.__new__(cls, *args)
     31 def __new__(cls, *args: str | "NodePath") -> "NodePath":
     32     obj = super().__new__(cls, *args)
---> 34     if obj.drive:
     35         raise ValueError("NodePaths cannot have drives")
     37     if obj.root not in ["/", ""]:

File C:\anaconda3\envs\my_env_01082024\Lib\pathlib.py:557, in PurePath.drive(self)
    555     return self._drv
    556 except AttributeError:
--> 557     self._load_parts()
    558     return self._drv

File C:\anaconda3\envs\my_env_01082024\Lib\pathlib.py:408, in PurePath._load_parts(self)
    407 def _load_parts(self):
--> 408     paths = self._raw_paths
    409     if len(paths) == 0:
    410         path = ''

AttributeError: 'NodePath' object has no attribute '_raw_paths'
```
Could someone try downloading the attached raw file? That way, we'll know if it's just my issue or not. Thank you

**Comment by ctuguinay** [comment]
@m4rkus84 I'll try converting in a short bit, but could you also try using Python 3.9-3.11. We dont support Python 3.12.

**Comment by ctuguinay** [comment]
I was able to convert with Python 3.9:

![image](https://github.com/user-attachments/assets/05454886-3b1a-428c-9823-390a2a9e59fe)

**Comment by ctuguinay** [comment]
Using Python 3.12, I got the same error as you:

![image](https://github.com/user-attachments/assets/b915ab79-a430-41da-bf21-937056befc95)

![image](https://github.com/user-attachments/assets/b7b2163d-0c42-412c-a288-69edb7c610e5)

**Comment by ctuguinay** [comment]
@m4rkus84 We're working on adding support for Python 3.12 since it has become the default for many people installing Python. Our CI tests support only 3.9-3.11 as of now.

Let me know when you've tried converting to Python 3.9-3.11 and I'll close this issue.

**Comment by m4rkus84** [comment]
Thank you for your patience and support. In the next few days, I will try downgrading Python to the version you suggested. I hope the Echopype project continues to function, grow, and expand, as it is one of the very few truly free and open-source routines for analyzing active acoustic data. Thanks again. You can close the thread.

**Comment by m4rkus84** [comment]
I confirm that the import of raw EK80 files into Echopype 0.9.0 works with Python 3.11.9 | packaged by Anaconda, Inc.
